Temporarily disable Embroider
The production build seems to fail with the following error:

> Error: Could not find module `frontend-centrale-vindplaats/app` imported from `~fastboot/app-factory`

This doesn't happen in the dev build, which is why we didn't notice.

So we disable Embroider until we find a solution.